remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-scholar

title: ""
description: [Welcome!]

scholar:
  style: ieee # You can use apa, ieee, mla, etc.
  locale: en
  source: _bibliography
  bibliography: publications.bib # Make sure this matches your filename
